#! /bin/bash

full='''
function clearPrint() {
	clear
	echo "$1"
}

frames=("8==mD" "8==mD" "8==mD" "8==mD" "8=m=D" "8=m=D" "8=m=D" "8=m=d" "8m==D" "8m==D" "8m==D" "8m==D" "8=m=D" "8=m=D" "8=m=D" "8=m=D")

for i in $(seq 1 10); do
	for frame in "${frames[@]}"; do
		clearPrint "$frame"
	done
done

clearPrint "8=m=D ~"
clearPrint "8=m=D ~~"
'''

mkdir -p /tmp/dontForgetTo
touch /tmp/dontForgetTo/lockYourLaptop.sh
chmod +x /tmp/dontForgetTo/lockYourLaptop.sh

cat <<EOF >/tmp/dontForgetTo/lockYourLaptop.sh
$full
EOF

echo "/tmp/dontForgetTo/lockYourLaptop.sh # lol don't forget to lock your laptop" >>~/.zshrc
